version: '3'

services:
  backend:       
    image: "cvitaa11/book-list-node:1.0"
    ports:
      - "4000:4000"
  frontend:    
    image: "cvitaa11/book-list-react:1.0"
    ports:
      - "81:80"
    links:
      - "backend:be"